added book logic
Kate892F/Online-book-store pull request #1
Opened 2024-12-04 13:43 UTC by Kate892F

2024-12-04 14:43 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments

2024-12-04 14:43 UTC, Elena-Bruyako commented on pom.xml
> +			<groupId>org.apache.commons</groupId>
remove dependency

2024-12-04 14:43 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/model/Book.java
> +@Data
```suggestion
@Getter
@Setter
```

2024-12-04 14:43 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/model/Book.java
> +@Table(name = "Books")
```suggestion
@Table(name = "books")
```

2024-12-04 14:43 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/repository/impl/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-12-04 14:43 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/repository/impl/BookRepositoryImpl.java
> +    }
```suggestion
```

2024-12-04 14:43 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/impl/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-12-04 14:43 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/impl/BookServiceImpl.java
> +    }
```suggestion
```

2024-12-05 07:15 UTC, liliia-ponomarenko approved these changes
LGTM!

2024-12-05 11:35 UTC, merged