second task
Kate892F/Online-book-store pull request #2
Opened 2024-12-05 17:58 UTC by Kate892F

2024-12-05 18:36 UTC, okuzan requested changes

2024-12-05 18:36 UTC, okuzan commented on src/main/java/com/bookstore/dto/CreateBookRequestDto.java
> +
```suggestion
```

2024-12-05 18:36 UTC, okuzan commented on src/main/java/com/bookstore/controller/imp/BookControllerImpl.java
> +public class BookControllerImpl implements BookController {
it's an overkill, let's simplify by removing controller interface

2024-12-06 11:45 UTC, Elena-Bruyako requested changes
See comments

2024-12-06 11:45 UTC, Elena-Bruyako commented on pom.xml
> +			<version>3.3.2</version>
```suggestion
```

2024-12-06 11:45 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-12-06 11:45 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/controller/BookController.java
> +    public BookDto getBookById(@PathVariable(name = "id") Long id) {
```suggestion
    public BookDto getBookById(@PathVariable Long id) {
```

2024-12-06 11:45 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new DataProcessingException("Failed to get books", e);
wrong message

2024-12-06 11:45 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/impl/BookServiceImpl.java
> +                () -> new EntityNotFoundException("Failed to find book by id: " + id)
It's better
```suggestion
                () -> new EntityNotFoundException("Cannot find book by id: " + id)
```

2024-12-07 09:25 UTC, Elena-Bruyako approved these changes

2024-12-07 11:04 UTC, merged